name: many_llm
description: AI Chat application template with simple design
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  lucide_icons: ^0.257.0
  flutter_markdown: ^0.7.4+1
  markdown: ^7.1.1
  flutter_highlight: ^0.7.0
  google_fonts: ^6.1.0
  http: ^1.2.0
  shared_preferences: ^2.0.0
  flutter_tts: ^4.0.0
  uuid: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

